export const TRIAL_LOG_SCHEMA_VERSION = "text-enrichment-trial-log-v2";

export const TRIAL_LOG_COLUMNS = Object.freeze([
  { name: "event_id", type: "string", required: true, description: "Idempotency key for one analyzed trial response." },
  { name: "participant_id", type: "string", required: true, description: "Pseudonymous Prolific participant identifier." },
  { name: "participant_slot", type: "integer", required: true, description: "Pre-generated allocation slot, 1–30." },
  { name: "set_id", type: "integer", required: true, description: "Study set, 1–3." },
  { name: "set_trial_index", type: "integer", required: true, description: "Trial position within the set, 1–38." },
  { name: "global_trial_index", type: "integer", required: true, description: "Trial position across the study, 1–114." },
  { name: "document_id", type: "string", required: true, description: "Document identifier." },
  { name: "condition_id", type: "string", required: true, description: "Enriched condition identifier." },
  { name: "enriched_file", type: "string", required: true, description: "HTML file used for the enriched version." },
  { name: "degree_value", type: "integer", required: true, description: "Ordered enrichment degree, 1–6." },
  { name: "baseline_side", type: "enum:left|right", required: true, description: "Screen side containing D0_plain." },
  { name: "document_exposure_number", type: "integer", required: true, description: "First, second, or third exposure to this document." },
  { name: "randomization_seed", type: "string", required: true, description: "Seed and set rotation used to reproduce trial order." },
  { name: "rating", type: "number", required: true, description: "Preference normalized to the enriched version: −3 to +3." },
  { name: "response_time", type: "number", required: true, description: "Rating response time in milliseconds." },
  { name: "session_id", type: "string", required: true, description: "Pseudonymous Prolific session identifier." },
  { name: "study_id", type: "string", required: true, description: "Prolific study identifier." },
  { name: "allocation_id", type: "string", required: true, description: "Immutable allocation identifier for the participant slot." },
  { name: "enriched_side", type: "enum:left|right", required: true, description: "Screen side containing the enriched version." },
  { name: "source_document_id", type: "string|null", required: false, description: "Source pipeline document UUID." },
  { name: "stimulus_validation_status", type: "string", required: false, description: "Source-pipeline validation status." },
  { name: "visual_coverage", type: "number|null", required: false, description: "Observed enrichment ink-mass ratio." },
  { name: "target_coverage", type: "number|null", required: false, description: "Target enrichment ink-mass ratio." },
  { name: "retained_factor_count", type: "integer|null", required: false, description: "Number of retained enrichment factors." },
  { name: "spatial_rating", type: "integer", required: true, description: "Raw left-to-right rating, −3 to +3." },
  { name: "planned_fixation_ms", type: "number", required: true, description: "Planned fixation duration." },
  { name: "planned_exposure_ms", type: "number", required: true, description: "Planned simultaneous stimulus duration." },
  { name: "actual_exposure_ms", type: "number", required: true, description: "Measured simultaneous stimulus duration." },
  { name: "preload_ms", type: "number", required: true, description: "Time used to preload and size the pair." },
  { name: "attempt_count", type: "integer", required: true, description: "Attempt number after discarded timing attempts." },
  { name: "stimulus_scale", type: "number", required: true, description: "Common scale applied to both documents." },
  { name: "source_viewport_width", type: "number", required: true, description: "Source stimulus width in CSS pixels." },
  { name: "source_viewport_height", type: "number", required: true, description: "Source stimulus height in CSS pixels." },
  { name: "fitted_content_height", type: "number", required: true, description: "Pair-locked content height used for fitting." },
  { name: "left_content_height", type: "number", required: true, description: "Measured left-document content height." },
  { name: "right_content_height", type: "number", required: true, description: "Measured right-document content height." },
  { name: "trimmed_bottom_whitespace_px", type: "number", required: true, description: "Unused bottom whitespace excluded from fit." },
  { name: "fullscreen", type: "boolean", required: true, description: "Whether the browser was in fullscreen mode." },
  { name: "display_info_json", type: "json", required: true, description: "Display and browser quality metadata." },
  { name: "responded_at", type: "datetime", required: true, description: "Client response timestamp." },
  { name: "study_version", type: "string", required: true, description: "Deployed study version." },
  { name: "received_at", type: "datetime", required: true, description: "Server receipt timestamp." }
]);

export const TRIAL_LOG_HEADERS = Object.freeze(TRIAL_LOG_COLUMNS.map((column) => column.name));

export const ALLOCATION_HEADERS = Object.freeze([
  "allocation_id",
  "participant_id",
  "participant_slot",
  "set_id",
  "set_trial_index",
  "global_trial_index",
  "document_id",
  "document_index",
  "condition_id",
  "enriched_file",
  "degree_value",
  "baseline_side",
  "enriched_side",
  "document_exposure_number",
  "randomization_seed",
  "rating",
  "response_time",
  "assignment_version",
  "study_version"
]);
